server:
  port: 8085

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: catalog-service
          uri: lb://movie-catalog-service
          predicates:
            - Path=/catalog/**
        - id: movie-info-service
          uri: lb://movie-info-service
          predicates:
            - Path=/movie/**
        - id: ratings-data-service
          uri: lb://ratings-data-service
          predicates:
            - Path=/rating/**